#pragma once

#include <string>
#include <vector>
#include <unordered_map>
#include <unordered_set>
#include <chrono>
#include <memory>

namespace logdog {

struct Transition {
    std::string target_node;
    int timeout_ms;
};

struct StateConfig {
    std::string name;
    std::string start_node;
    std::vector<Transition> transitions;
    std::string description;
};

struct ActiveState {
    std::string name;
    size_t current_transition_idx;
    std::chrono::steady_clock::time_point last_activation;
};

// Event types to send back to Python
enum class EventType {
    StateActivated,
    StateCompleted,
    Timeout,
    StateInterrupted,
    EntryDetected,
    EngineLog
};

struct EventData {
    EventType type;
    std::string state_name;
    std::string node_name;
    std::string description;
    int elapsed_ms;
};

class StateMachine {
public:
    StateMachine();
    
    void add_state_config(const StateConfig& config);
    void set_completion_nodes(const std::unordered_set<std::string>& nodes);
    void add_entry_node(const std::string& node_name, const std::string& name, const std::string& desc);

    // Returns a list of events generated by this node processing
    std::vector<EventData> process_node(const std::string& node_name);
    
    // Check timeouts
    std::vector<EventData> check_timeouts();

private:
    std::unordered_map<std::string, StateConfig> configs_;
    std::unordered_map<std::string, ActiveState> active_states_;
    std::unordered_set<std::string> completion_nodes_;
    
    // Map node_name -> Entry Info
    struct EntryInfo { std::string name; std::string desc; };
    std::unordered_map<std::string, EntryInfo> entry_nodes_;
};

} // namespace logdog